name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  building:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm i && lerna exec -- npm i && lerna bootstrap
      - name: Build
        run: lerna exec -- npm run build
